version: '3'

services:
  wp:
    image: wordpress:${WP_VER}  
    volumes:
      - www_html:/var/www/html
      - db_exchange:/db_exchange
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: "true"
    depends_on:
      - db
      
