version: '3'
services:
  wp:
    build:
      context: .devcontainer/
    volumes:
      - www_html:/var/www/html
      - db_exchange:/db_exchange
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_NAME: "DATABASE"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "PASSWORD"
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: | 
          $$_host = $$_SERVER['HTTP_X_FORWARDED_HOST'] ?? $$_SERVER['HTTP_HOST']; 
          $$_SERVER['HTTP_HOST'] = $$_host;
          $$_proto = $$_SERVER['HTTP_X_FORWARDED_PROTO'] ?? 'http'; 
          $$_url = $$_proto.'://'.$$_host.'/'; 
          define( 'WP_HOME', $$_url); 
          define( 'WP_SITEURL', $$_url); 
    depends_on:
      - db
    init: true   
    network_mode: service:db

    # for strace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  db:
    image: mariadb:latest
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--max_allowed_packet=256M', 
        '--character-set-server=utf8mb4', 
        '--collation-server=utf8mb4_unicode_520_ci'
        ]
    volumes:
      - db_exchange:/db_exchange
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "DATABASE"
      MYSQL_ROOT_PASSWORD: "PASSWORD"
      
volumes:
  db_exchange:
  www_html:
  db_data:
